config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#tutorial'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get "/download/:id", to: "invs#download", as: "inv_download"
  get "/download_group/:id", to: "groups#download", as: "group_download"
  
  get "/search_invoices/", to: "invs#search", as: "invoice_search"
  
  post "/tutorial_1/", to: "users#tutorial_1", as: "tutorial_1"
  post "/tutorial_3/", to: "users#tutorial_3", as: "tutorial_3"
  get "/tutorial_complete/", to: "users#tutorial_complete", as: "tutorial_complete"
  
  
  
  
  resources :invs do
    resources :lines
  end
  
  resources :lines do
    put :order, on: :collection
  end
  
  resources :toplines do
    put :order, on: :collection
  end
  
  
  resources :users 
  resources :groups
  resources :coverimages
  
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, presence: true
  
  has_many :invs
  belongs_to :user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  respond_to :html, :js
  
  before_action :correct_user,   only: [:edit, :update, :show, :delete, :download]
  before_action :logged_in_user
  
  def new
    @group = Group.new
    
    @invs = Inv.all.where(user_id: current_user.id).reverse 
    @groups = Group.all.where(user_id: current_user.id).reverse
    
  end
  
  
  def create
    @group = current_user.groups.create(group_params)
    
    @invs = Inv.all.where(user_id: current_user.id).reverse 
    @groups = Group.all.where(user_id: current_user.id).reverse
    
  
    
    if @group.valid?
      flash.now[:success] = "Successfully created group"
      @invs = Inv.all.where(user_id: current_user.id).reverse
      @group = Group.all.where(user_id: current_user.id).reverse #finds all groups created by current user
      redirect_to new_group_path

    else
      flash.now[:danger] = 'something went wrong'
    end
    
  end
  
  
  def index
    @groups = Group.all.where(user_id: current_user.id).reverse
  end
  
  
  def show
    @group = Group.find(params[:id])
    @groups = Group.all.where(user_id: current_user.id).reverse
    @groupinvs = @group.invs.all
    @invs = Inv.all.where(user_id: current_user.id).reverse 
  end
  
  
  def download
    @group = Group.find(params[:id])
    makepdfgroup(@group)
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.invs.each do |inv| 
      inv.group_id = nil
      inv.save
    end
    @group.destroy
    
    @invs = Inv.all.where(user_id: current_user.id).reverse 
    @groups = Group.all.where(user_id: current_user.id).reverse
    
  end
  
  private

  def group_params
    params.require(:group).permit(:name)
  end
  
  
  def correct_user
    @user = Group.find(params[:id]).user
    redirect_to(root_url) unless current_user?(@user)
  end

  
end

app/helpers/groups_helper.rb
module GroupsHelper
  
  def makepdfgroup(group)
    
        ##############################################
      #######DIRECTORY MAKING SECTION###########
    #############################################
  
    
    if File.directory?("invoices") == false
      Dir.mkdir("invoices")
    end
    
    if File.directory?(group.user.name) == false
      FileUtils::mkdir_p "invoices/" + group.user.name
    end
    
    group_length = group.invs.count
      
    Prawn::Document.generate("invoices/" + group.user.name + "/invoice" + group.id.to_s +  ".pdf") do
      group.invs.each_with_index do |y, y2|

        pdf_method(y)
        
        if y2 != group_length - 1
          start_new_page 
        end
        
      end
      
    end
    download_pdf_group(group)
    
  end
  
  

  def download_pdf_group(inv)
    send_file(
      "#{Rails.root}/invoices/" + inv.user.name + "/invoice" + inv.id.to_s +  ".pdf",
      filename: "invoice" + inv.id.to_s +  ".pdf",
      type: "application/pdf"
    )
  end
  
end

app/views/groups/create.js.erb
$( ".dashboard-right" ).fadeOut( "fast", function() {

  $('.dashboard-right').html("<%= j (render "invs/newpage.html.erb") %>"); // renders the form for the invoice you jsut made
  $('.left-invoices-container').html("<%= j (render "layouts/inv_search.html.erb") %>"); //renders the search
  
  
  $('.iframe-container').html(""); // renders the search 
  $(".right-tab").hide()
  
  
  $( ".dashboard-right" ).fadeIn( "fast")
});

app/views/groups/destroy.js.erb
$( ".dashboard-right" ).fadeOut( "fast", function() {

  $('.dashboard-right').html("<%= j (render "groups/newgroup.html.erb") %>"); // renders the form for the invoice you jsut made
  $('.left-invoices-container').html("<%= j (render "layouts/inv_search.html.erb") %>"); //renders the search
  
  
  $('.iframe-container').html(""); // renders the search 
  $(".right-tab").hide()
  
  
  $( ".dashboard-right" ).fadeIn( "fast")
});

app/views/groups/new.html.erb
<div class="group-wrapper">
  <div class="group-form-container">
  
    <div class="dashboard-right-container">
      <div class="dashboard-right">
        <div class="right-inner-container">
          <div class="right-inner">
            <h3 class="tk-refrigerator-deluxe">New Group</h3>
          </div>
        </div>
        
        <div class="right-form-container">
          
          <%= form_for (Group.new) do |f| %>
            <div class="group-container-new">
              <p class="recipient-form-title-new tk-refrigerator-deluxe">Group Name</p>
              <%= f.text_field :name, autofocus: true, class: "recipient-form-dashboard-new tk-proxima-nova", :autocomplete => :off %>
            </div>
            <%= f.submit "Create", class: "new-button-group tk-refrigerator-deluxe" %>
            
          <% end %>
        </div>
        
  
      </div>
    </div>
  
  </div>
  
  <div class="groups-container">
    <div class="group-all"> 
      <h3 class="dropdown-invoices-title tk-refrigerator-deluxe" style="padding-bottom: 10px;">All Groups</h3>
      
      <div class="dropdown-padding"></div> <!-- padding so the scroll bar looks correct -->
        
      <div class="dropdown-invoices-inner"> <!-- contains the rendered invoices -->
       <% @groups.each do |group| %>
        <a href="/groups/<%= group.id.to_s %>" >
          
          <div class="invoice-header-container">
          <% if group.name.length > 19 %>
            <p class="invoice-header-container-name tk-refrigerator-deluxe"><%= group.name[0..18] + "..." %></p>
          <% else %>
            <p class="invoice-header-container-name tk-refrigerator-deluxe"><%= group.name %></p>
          <% end %>
          <p class="invoice-header-container-date tk-proxima-nova">Contains <%= group.invs.count.to_s %> invoices</p>
          </div>
  
        </a>
      <% end %>
      </div>
        
      <div class="dropdown-padding"></div> <!-- padding so the scroll bar looks correct -->
      
      <% if current_user.groups.count < 1 %>
      
        <div class="no-results">
          <i class="fa fa-frown-o fa-4x"></i>
          <p>You haven't made any<br>groupoices yet!</p>
        </div>
      
      <% elsif @groups.count == 0 %>
        <div class="no-results">
          <i class="fa fa-frown-o fa-4x"></i>
          <p>No items found matching <br> that search!</p>
        </div>
      <% end %>
          
    </div>
  </div>
</div>

app/views/groups/new.js.erb
$( ".dashboard-right" ).fadeOut( "fast", function() {

  $('.dashboard-right').html("<%= j (render "groups/newgroup.html.erb") %>"); // renders the form for the invoice you jsut made
  $('.left-invoices-container').html("<%= j (render "layouts/inv_search.html.erb") %>"); //renders the search
  
  
  $('.iframe-container').html(""); // renders the search 
  $(".right-tab").hide()
  
  
  $( ".dashboard-right" ).fadeIn( "fast")
});

app/views/groups/show.html.erb
<div class="group-wrapper">
  <div class="group-show-container">
  
    <div class="dashboard-right-container">
      <div class="dashboard-right">
        <div class="right-inner-container">
          <div class="right-inner">
            <h3 class="tk-refrigerator-deluxe"><%= @group.name %></h3>
          </div>
        </div>
        
        <div class="right-form-container">
          
          <div class="group-all-show"> 
            <h3 class="dropdown-invoices-title tk-refrigerator-deluxe" style="padding-bottom: 10px;">Invoices</h3>
            
            <div class="dropdown-padding"></div> <!-- padding so the scroll bar looks correct -->
              
            <div class="dropdown-invoices-inner" style="height:380px"> <!-- contains the rendered invoices -->
            <% @group.invs.each do |inv| %>
              <a href="/invs/<%= inv.id %>/edit">
               <div class="invoice-header-container">
                  <% if inv.recipient.length > 19 %>
                    <p class="invoice-header-container-name tk-refrigerator-deluxe"><%= inv.recipient[0..18] + "..." %></p>
                  <% else %>
                    <p class="invoice-header-container-name tk-refrigerator-deluxe"><%= inv.recipient %></p>
                  <% end %>
                  <p class="invoice-header-container-date tk-proxima-nova"><%= inv.created_at.to_s[0..9] %></p>
                </div>
                </a>
              <% end %>
              
              <% if current_user.invs.count < 1 %>
              
                <div class="no-results">
                  <i class="fa fa-frown-o fa-4x"></i>
                  <p>You haven't made any<br>invoices yet!</p>
                </div>
              
              <% elsif @invs.count == 0 %>
                <div class="no-results">
                  <i class="fa fa-frown-o fa-4x"></i>
                  <p>No items found matching <br> that search!</p>
                </div>
              <% end %>
            </div>
              
            <div class="dropdown-padding"></div> <!-- padding so the scroll bar looks correct -->
                
          </div>
          <div class="group-list-container">
            <ul>
              <li><a href="/groups/<%= @group.id %>" data-method="delete" data-confirm="Are you sure you want to delete this group?" class="delete-button tk-refrigerator-deluxe">Delete</li>
              <li><%= link_to "Download", group_download_path(@group.id), class: "delete-button tk-refrigerator-deluxe" %></li>
            </ul>
          </div>
        </div>
        
  
      </div>
    </div>
  
  </div>
  
  <div class="groups-container">
    <div class="group-all"> 
      <h3 class="dropdown-invoices-title tk-refrigerator-deluxe" style="padding-bottom: 10px;">All Groups</h3>
      
      <div class="dropdown-padding"></div> <!-- padding so the scroll bar looks correct -->
        
      <div class="dropdown-invoices-inner"> <!-- contains the rendered invoices -->
       <% @groups.each do |group| %>
        <a href="/groups/<%= group.id.to_s %>" >
          
          <div class="invoice-header-container">
          <% if group.name.length > 19 %>
            <p class="invoice-header-container-name tk-refrigerator-deluxe"><%= group.name[0..18] + "..." %></p>
          <% else %>
            <p class="invoice-header-container-name tk-refrigerator-deluxe"><%= group.name %></p>
          <% end %>
          <p class="invoice-header-container-date tk-proxima-nova">Contains <%= group.invs.count.to_s %> invoices</p>
          </div>
  
        </a>
      <% end %>
      </div>
        
      <div class="dropdown-padding"></div> <!-- padding so the scroll bar looks correct -->
      
      <% if current_user.groups.count < 1 %>
      
        <div class="no-results">
          <i class="fa fa-frown-o fa-4x"></i>
          <p>You haven't made any<br>groupoices yet!</p>
        </div>
      
      <% elsif @groups.count == 0 %>
        <div class="no-results">
          <i class="fa fa-frown-o fa-4x"></i>
          <p>No items found matching <br> that search!</p>
        </div>
      <% end %>
          
    </div>
  </div>
</div>