config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#tutorial'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get "/download/:id", to: "invs#download", as: "inv_download"
  get "/download_group/:id", to: "groups#download", as: "group_download"
  
  get "/search_invoices/", to: "invs#search", as: "invoice_search"
  
  post "/tutorial_1/", to: "users#tutorial_1", as: "tutorial_1"
  post "/tutorial_3/", to: "users#tutorial_3", as: "tutorial_3"
  get "/tutorial_complete/", to: "users#tutorial_complete", as: "tutorial_complete"
  
  
  
  
  resources :invs do
    resources :lines
  end
  
  resources :lines do
    put :order, on: :collection
  end
  
  resources :toplines do
    put :order, on: :collection
  end
  
  
  resources :users 
  resources :groups
  resources :coverimages
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  
  has_secure_password
  #validates :name, presence: true, uniqueness: { case_sensitive: false }
  
  
  validates :name, presence: true, uniqueness: true, :on => :create
  validates_format_of :name, :with => /\A(?=.*[a-z])[a-z\d]+\Z/i, :on => :create
  validates :password, presence: true, :on => :create
  validates :password_confirmation, presence: true, :on => :create
  
  has_many :invs
  has_many :groups
  has_many :coverimages
  has_many :toplines
  
  
  
    # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :correct_user,   only: [:edit, :update, :show]
  before_action :logged_in_user, only: [:edit, :update, :tutorial_1, :tutorial_3]
  
  def new
    redirect_to root_url if logged_in?
    @user = User.new
  end
  
  def create
    
    @user = User.create(user_params)
    
    if @user.valid?
      @user.toplines.create(name: "ADDRESS", value: "Your Address")
      @user.toplines.create(name: "MOBILE", value: "Your Mobile/Cell")
      @user.toplines.create(name: "PHONE", value: "Your Phone")
      @user.toplines.create(name: "EMAIL", value: "Your Email")
      
      @user.invs.create(recipient: "Test Recipient", address_1: "26 Test Street, \n Test City")
      log_in @user
      redirect_to root_url
      
    else
      flash[:danger] = "Invalid username/password"
      redirect_to new_user_path
    end
    
  end
  
  def edit
    @user = User.find(params[:id])
    
    @coverimage = @user.coverimages.first
    @previewinv = @user.invs.first
    
    @invs = Inv.all.where(user_id: current_user.id).reverse 
    @toplines = current_user.toplines.all

  end
  
  def update
    @user = User.find(params[:id]) 
    
    @invs = Inv.all.where(user_id: current_user.id).reverse
      
    @coverimage = @user.coverimages.first
    @previewinv = @user.invs.first
    @toplines = current_user.toplines.all
      
    if @user.update_attributes(user_params)
      flash[:success] = "Successfully Updated"
    else
      flash[:danger] = "Oops, something went wrong"
    end
    
  end
  
  def tutorial_1
    @user = current_user
    @user.sender = params[:data]
    @user.save
    @toplines = current_user.toplines.all
  end
  
  def tutorial_3
    @user = current_user
    @user.topoffset = params[:data]
    @user.save
  end
  
  def tutorial_complete
    @user = current_user
    @user.tutorial_complete = true if @user.tutorial_complete == false
    @user.save
    puts @user.name + "tut complete!"
    render :nothing => true
  end
  
  
  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email, :invoice_email, :address, :phone, :mobile, :topoffset, :sender, :use_picture)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_editform.html.erb
<div class="right-inner-container">
  <div class="right-inner">
    <h3>Updating User Info</h3>
  </div>
  
  <div class="right-inner-two">
    <h3></h3>
  </div>
</div>

<div class="right-body">


<h4 class="edit-user-h4">These Will Appear at the top of each invoice you make:</h4>

<%= form_for @user, :remote => true do |f| %>
  
  
<div class="edit-user-sender">
  <%= f.label "You or your companies name: " %>
  <%= f.text_field :sender %>
</div>
  

<div class="edit-user-topoffset">
  <%= f.label "Offset" %>
  <%= f.text_field :topoffset%>
</div>

<div class="edit-user-topoffset">
  <%= f.label "Use a picture instead of the name of your organisation" %>
  <%= f.check_box :use_picture, class: "check-box2"  %>
</div>
  
<%= f.submit "Update", class: "line-button" %>
<% end %>

<div style="display:inline-block">
  <% if current_user.coverimages.count == 0 %>
  <h4 class="edit-user-h4">Add a cover Image </h4>
  
    <%= form_for Coverimage.new, :remote => true do |f| %>
      <%= f.file_field :file %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= f.submit "Change cover image", class: "image-button" %>
    <% end %>
  <% else %>
  <h4 class="edit-user-h4">Update cover image</h4>
    <%= form_for @coverimage,:remote => true do |f| %>
      <%= f.file_field :file %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= f.submit "Change cover image", class: "image-button" %>
    <% end %>
  
      <img style="width:300px" src="/coverimages/<%= @coverimage.id %>">
  
  <% end %>
</div>

<div style="display:inline-block; width: 800px; margin-left: 10px">
  
  <h4 class="edit-toplines-h4">Add contact info</h4>
  
  <%= form_for [Topline.new], :remote => true do |f| %>
    <div class="edit-user-sender">
      <%= f.text_field :name, placeholder: "name" %>
      <%= f.text_field :value, placeholder: "value" %>
      <%= f.submit "Submit" %>
    </div>
  <% end %>

  <ul class="sortable2">
    
  <% @toplines.each do |x| %>
    
    <li data-id="<%= x.id %>"> <!-- Nescessary for the sorting -->
    
    <div class="line line<%=x.id%>">
      
        <p class="service-paragraph"><%= x.name %>:</p>
        
        <p class="description-paragraph"><%= x.value %></p>
        
        <%= link_to 'X', x, :method => :delete, class: "delete-button", :remote => true %>
        <%= link_to 'edit', edit_topline_path(x), class: "edit-button", :remote => true %>
  
    </div>
    
      <div class="line line<%=x.id%>-form" style="display:none"> <!-- form for edit is displayed here -->
      </div>
    
    </li>
  
  <% end %>
  
  </ul>

</div>


<script type="text/javascript"> //reapplies the sorting thing every time the partial is reloaded.
    ready();
</script>
</div>

app/views/users/_edituser.html.erb
<div class="edit-user-forms-container">
  <h4 class="edit-user-h4 tk-refrigerator-deluxe">Editing Details</h4>
  
  <%= form_for @user, :remote => true do |f| %>
    

  <div class="company-container">
    <p class="company-title tk-refrigerator-deluxe">You or Your Organisation's Name</p>
    <%= f.text_field :sender, class: "company-form tk-proxima-nova" %>
  </div>
  
  <div class="divider"></div>
  
  <div class="company-container">
    <p class="top-offset-title tk-refrigerator-deluxe">Details Offset</p>
    <%= f.text_field :topoffset, class: "top-offset-form tk-proxima-nova" %>
  </div>
  
  <% if current_user.coverimages.count > 0 %>
    <div class="company-container" style="margin-bottom: 0px">
      <p class="top-offset-title tk-refrigerator-deluxe" style="padding-bottom: 2px;">Use Cover Image</p>
      <%= f.check_box :use_picture, class: "check-box2"  %>
    </div>
  <% end %>
    
  <%= f.submit "Update", class: "edit-user-button tk-refrigerator-deluxe" %>
  <% end %>
</div>

<div class="edit-user-image-container">
  <% if current_user.coverimages.count == 0 %>
  <h4 class="edit-user-h4 tk-refrigerator-deluxe">Add Cover Image </h4>
  
    <%= form_for Coverimage.new, :remote => true do |f| %>
      <%= f.file_field :file, class: "file-field tk-proxima-nova" %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= f.submit "Change cover image", class: "edit-image-button tk-refrigerator-deluxe" %>
    <% end %>
  <% else %>
  <h4 class="edit-user-h4 tk-refrigerator-deluxe">Update Cover Image</h4>
    <%= form_for @coverimage,:remote => true do |f| %>
      <%= f.file_field :file, class: "file-field tk-proxima-nova" %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      
      <%= f.submit "Change cover image", class: "edit-image-button tk-refrigerator-deluxe" %>
      
    <% end %>
  <img style="width:300px" src="/coverimages/<%= @coverimage.id %>">
      
  
  <% end %>
</div>


<div class="tutorial-toplines-container-2">
  <%= render "users/partials/toplines.html.erb" %>
</div>

<script type="text/javascript"> //reapplies the sorting thing every time the partial is reloaded.
  ready();
</script>

app/views/users/_iframe.html.erb
<div class="iframe-inner">
  <% if current_user.invs.count == 0 %>
  
    <div style:"width:600px;height:700px;background-color: black">
        <div class="no-results">
        <i class="fa fa-frown-o fa-4x"></i>
        <p>You need to make an invoice<br> before you can preview<br> these changes</p>
        </div>
    </div>
    
  <% else %>
    <iframe src="<%= asset_path "invs/" + current_user.invs.first.id.to_s %>" width="100%" height="100%"></iframe>
  <% end %>
  
</div>

app/views/users/_pdf.html.erb
<div class="iframe-inner">
  <% if current_user.invs.count == 0 %>
  
    <div style:"width:600px;height:700px;background-color: black">
        <div class="no-results">
        <i class="fa fa-frown-o fa-4x"></i>
        <p>You need to make an invoice<br> before you can preview<br> these changes</p>
        </div>
    </div>
    
  <% else %>
    <iframe src="<%= asset_path "invs/" + current_user.invs.first.id.to_s %>" width="100%" height="100%"></iframe>
  <% end %>
  
</div>

app/views/users/edit.html.erb
<div class="dashboard-container">

  <div class="edit-user-container">
      <%= render "users/edituser.html.erb" %>
  </div>
  
  
  <div class="iframe-container-user" style="display:inline-block" style="display:none">
    <%= render "users/iframe.html.erb" %>
  </div>

</div>

app/views/users/new.html.erb
<div class="log-in-page-container">
   <h1 class="not-logged-in-header tk-moby-monospaced">Invoice Factory</h1>
   <p class="not-logged-in-info tk-proxima-nova">Invoice Factory lets you easily create professional looking invoices, log in to get started.</p>

   
   <h1 class="log-in-title tk-refrigerator-deluxe">Creating Account</h1>
   
   <%= form_for @user do |f| %>
   
      <div class="username-container">
         <%= f.label :username, class: "username-label tk-refrigerator-deluxe" %>
         <%= f.text_field :name, autofocus: true, class: "username-form tk-proxima-nova" %>
      </div>
      
      <div class="password-container">
         <%= f.label :password, class: "password-label tk-refrigerator-deluxe" %>
         <%= f.password_field :password,class: 'password-form tk-proxima-nova' %>
      </div>
         
      <div class="password-container-confirm">
         <%= f.label "Confirm Password", class: "password-label tk-refrigerator-deluxe" %>
         <%= f.password_field :password_confirmation, class: 'password-form tk-proxima-nova' %>
         
         <%= f.submit "Sign Up ", class: "log-in-button tk-refrigerator-deluxe" %>
      </div>
      
         

   

   <% end %>
     

</div>

app/views/users/tutorial_1.js.erb
$('.tutorial-1-confirm').html("")
$('.tutorial-1-confirm').html("<%= j (render "users/partials/tutorial_part_1.html.erb") %>");
$('.iframe-container').html("<%= j (render "users/iframe.html.erb") %>");<!-- renders the search -->

app/views/users/tutorial_3.js.erb
$('.iframe-container').html("<%= j (render "users/iframe.html.erb") %>");<!-- renders the search -->

app/views/users/update.html.erb
$( ".dashboard-right" ).fadeOut( "fast", function() {

  $('.dashboard-right').html("<%= j (render "users/editform.html.erb") %>"); <!-- renders the form for the invoice you jsut made -->
  $('.left-invoices-container').html("<%= j (render "layouts/inv_search.html.erb") %>"); <!-- renders the search -->
  
  
  $('.iframe-container').html("<%= j (render "users/pdf.html.erb") %>");<!-- renders the search -->
  hideDiv(".dashboard-left-container")
  showDiv(".iframe-container")

  $( ".dashboard-right" ).fadeIn( "fast")
  
});

app/views/users/update.js.erb
$('.iframe-container-user').html("<%= j (render "users/iframe.html.erb") %>");