config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#tutorial'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get "/download/:id", to: "invs#download", as: "inv_download"
  get "/download_group/:id", to: "groups#download", as: "group_download"
  
  get "/search_invoices/", to: "invs#search", as: "invoice_search"
  
  post "/tutorial_1/", to: "users#tutorial_1", as: "tutorial_1"
  post "/tutorial_3/", to: "users#tutorial_3", as: "tutorial_3"
  get "/tutorial_complete/", to: "users#tutorial_complete", as: "tutorial_complete"
  
  
  
  
  resources :invs do
    resources :lines
  end
  
  resources :lines do
    put :order, on: :collection
  end
  
  resources :toplines do
    put :order, on: :collection
  end
  
  
  resources :users 
  resources :groups
  resources :coverimages
  
  
end

app/models/inv.rb
class Inv < ActiveRecord::Base
  belongs_to :user
  has_many :lines
  belongs_to :group
  
  validates :recipient, presence: true
end

app/controllers/invs_controller.rb
class InvsController < ApplicationController
  respond_to :html, :js
  
  before_action :correct_user,   only: [:edit, :update, :show, :download, :delete]
  before_action :logged_in_user
  
  
  def new #Dont actually need this
    @inv = Inv.new
    @group = Group.all.where(user_id: current_user.id).reverse #finds all groups created by current user
    @invs = Inv.all.where(user_id: current_user.id).reverse 
    @total = get_total(@inv)
    
    @recipients = []
    @invs.each {|x| @recipients << [x.recipient, x.address_1, x.address_2, x.address_3] }
    
  end
  
  
  def edit #don't think i need this
    @inv = Inv.find(params[:id])
    @invs = Inv.all.where(user_id: current_user.id).reverse 
    @lines = @inv.lines.all
    @line = @inv.lines.new
    
    @group = Group.all.where(user_id: current_user.id).reverse #finds all groups created by current user
    
    @total = get_total(@inv)
  end
  
  
  
  
  
  def download #Actual download link
    @inv = Inv.find(params[:id])
    makepdf(@inv)
  end
  
  def show #just displays the pdf, hence the true param
    @inv = Inv.find(params[:id])
    makepdf(@inv, true)
  end
  
  

  
  def update
    @inv = Inv.find(params[:id]) 
    if @inv.update_attributes(inv_params)
      flash.now[:success] = "Invoice Saved"
      
      @invs = Inv.all.where(user_id: current_user.id).reverse 
      @lines = @inv.lines.all
      @line = @inv.lines.new
      @group = Group.all.where(user_id: current_user.id).reverse #finds all groups created by current user
      @total = get_total(@inv)
      
    else
      unless @inv.total.is_a? Integer
        flash.now[:danger] = "A total must be a number"
      else
        flash.now[:danger] = "Oops, something went wrong! Did you leave the name field blank?"
      end
    end
    
  end
  
  
  def index
    @invs = Inv.all.where(user_id: current_user.id) 
  end


  def create
    @inv = current_user.invs.create(inv_params) #the invoice being created
    @invs = Inv.all.where(user_id: current_user.id).reverse #invoices for the search bar
    
    if @inv.valid?
      
        
      @lines = @inv.lines.all
      @line = @inv.lines.new
      @group = Group.all.where(user_id: current_user.id).reverse #finds all groups created by current user
      @total = get_total(@inv)
      redirect_to edit_inv_path(@inv.id)
      
    else
      flash.now[:danger] = 'something went wrong, ensure you provided a recipient'
      
    end
  end
  
  
  
  def destroy
    @inv = Inv.find(params[:id])
    @inv.destroy
    @invs = Inv.all.where(user_id: current_user.id).reverse 
    @lines = @inv.lines.all
    @line = @inv.lines.new
    @group = Group.all.where(user_id: current_user.id).reverse #finds all groups created by current user
    @total = get_total(@inv)
    
    redirect_to root_url
  end
  
  
  def search
    @invs = Inv.all.where("recipient like ? ", "%#{params[:search]}%").where(user_id: current_user.id).reverse
  end
  
  
  private

  def inv_params
    params.require(:inv).permit(:recipient, :group_id, :total, :block, :address_1, :address_2, :address_3, :date, :due_date, :note)
  end
  
  def correct_user
    @user = Inv.find(params[:id]).user
    redirect_to(root_url) unless current_user?(@user)
  end

  
end

app/helpers/invs_helper.rb
include ApplicationHelper
module InvsHelper
  
  
  
  
  def makepdf(inv, display=false) #display is used by the iframe method to only show the pdf and not download it

    
    
    if File.directory?("invoices") == false #makes the invoices folder if it doesn't exist
      Dir.mkdir("invoices")
    end
    
    if File.directory?(inv.user.name) == false #makes a folder for the user in the invoices folder if it doesn't exist
      FileUtils::mkdir_p "invoices/" + inv.user.name
    end
  
    Prawn::Document.generate("invoices/" + inv.user.name + "/invoice" + inv.id.to_s +  ".pdf") do
      pdf_method(inv)
    end
    
    
    
    
    if display 
      showpdf(inv) #shows the file instead of downloading it
    else
      downloadpdf(inv) #sends the file for download after it's created
    end
    
  end
  
  
  
  
  def showpdf(inv)
    send_file(
      "#{Rails.root}/invoices/" + inv.user.name + "/invoice" + inv.id.to_s +  ".pdf",
      filename: "invoice" + inv.id.to_s +  ".pdf", :disposition => 'inline', 
      type: "application/pdf"
    )
  end
  
  def downloadpdf(inv)
    send_file(
      "#{Rails.root}/invoices/" + inv.user.name + "/invoice" + inv.id.to_s +  ".pdf",
      filename: "invoice" + inv.id.to_s +  ".pdf", 
      type: "application/pdf"
    )
  end


end

app/views/invs/_editpage.html.erb
<div class="right-inner-container">
  <div class="right-inner">
    <h3 class="tk-refrigerator-deluxe">Editing Invoice for: <%= link_to @inv.recipient, 'javascript:;', :remote => :true, class: "recipient-button-edit" %></h3>
    
    <div class="right-inner-form">
      <%= form_for (@inv), :remote => :true do |f| %>
        <%= f.text_field :recipient, autofocus: true, class: "recipient-form-dashboard-edit tk-proxima-nova" %>
      <% end %>
    </div>
  </div>

  
  <div class="right-inner-two">
    <h3 class="tk-refrigerator-deluxe">Total: £ <%= link_to @total.to_s, 'javascript:;', :remote => :true, class: "total-button-edit" %></h3>
  
  
    <div class="right-inner-two-form">
      <%= form_for (@inv), :remote => :true do |f| %>
        <%= f.text_field :total, autofocus: true, class: "total-form-dashboard-edit tk-proxima-nova" %>
      <% end %>
    </div>
    
  </div>
</div>

<div class="right-body">
  
    <%= form_for (@inv), :remote => :true do |f| %>
    
    
      <div class="date-container">
        <p class="date-form-title tk-refrigerator-deluxe">Sent</p>
        <%= f.text_field :date, :placeholder => "Date", class: "date-form-dashboard tk-proxima-nova", :autocomplete => :off %>
      </div>
        
      <div class="date-container">
        <p class="date-form-title tk-refrigerator-deluxe">Due</p>
          <%= f.text_field :due_date, :placeholder => "Date", class: "date-form-dashboard tk-proxima-nova", :autocomplete => :off %>
      </div>
      
      <div class="group-container">
        <p class="group-form-title tk-refrigerator-deluxe">Group </p>
        <%= f.collection_select :group_id, @group,:id,:name, :prompt => "None", class: "group-form-dashboard" %>
      </div>
      
      <div class="note-container">
        <p class="note-form-title tk-refrigerator-deluxe">Note </p>
        <%= f.text_area :note, class: "note-form-dashboard tk-proxima-nova"%>
      </div>
      
      <div class="address-container">
        <p class="address-form-title tk-refrigerator-deluxe">Address </p>
        <%= f.text_area :address_1, class: "address-form-dashboard tk-proxima-nova"%>
      </div>
      
      <%= f.submit "Update", class: "dashboard-form-button tk-refrigerator-deluxe"%>
      
    <% end %>

  <a  href="/download/<%=@inv.id%>">
    <i class="fa fa-arrow-circle-down fa-3x"></i>
  </a>
  
  <a class="change-mode" href="javascript:void(0)">
    <i class="fa fa-pencil-square-o fa-3x"></i>
  </a>
  
  <a href="/invs/<%=@inv.id%>" rel="nofollow" data-method="delete" data-confirm="Are you sure you want to delete this invoice?">
   <i class="fa fa-trash-o fa-3x"></i>
  </a>



<div class="line-mode">
  
  <div class="new-line-form">
      
    <h4 class="new-line-form-title tk-refrigerator-deluxe">Add Line</h4>
    <%= form_for [@inv, Line.new], :remote => true do |f| %>
    
      <%= f.text_field :service, autofocus: true, class: "service tk-proxima-nova", input_html: {autocomplete: 'off'},:placeholder => "Service" %>
      
      <%= f.text_area :description, class: "description tk-proxima-nova", input_html: {autocomplete: 'off'},:placeholder => "Description" %>
      
      <%= f.text_field :quantity, class: "quantity tk-proxima-nova", input_html: {autocomplete: 'off'},:placeholder => "Quantity" %>
   
      <%= f.text_field :price, class: "price tk-proxima-nova", input_html: {autocomplete: 'off'},:placeholder => "Price" %>
  
      <%= f.submit "Add", class: "line-button tk-refrigerator-deluxe" %>
    
    <% end %>
  </div>
  

  
  
  <div class="line-container">
   <ul class="sortable">
  
    <% @lines.each do |x| %>
      
      <li data-id="<%= x.id %>"> <!-- Nescessary for the sorting -->
      <div class="line line<%=x.id%>">
        
        <div class="line-left">
          <% unless x.service == "" %> <!-- will print the description is one is provided -->
            <p class="service-paragraph tk-refrigerator-deluxe"><%= x.service %>:</p>
          <% end %>
          
          <p class="description-paragraph tk-proxima-nova"><%= x.description %></p>
        </div>
        
        <%= link_to 'x', x, :method => :delete, class: "delete-button tk-refrigerator-deluxe", :remote => true %>
        <%= link_to 'edit', edit_line_path(x), class: "edit-button tk-refrigerator-deluxe", :remote => true %>
        
     
        
        
        <% unless x.price.nil? %> <!-- will print the price is one is provided -->
          <p class="price-paragraph tk-refrigerator-deluxe">£<%= '%.2f' % x.price %></p>
        <% end %>
        
         <% unless x.quantity.nil? %> <!-- will print the price is one is provided -->
          <p class="quantity-paragraph tk-refrigerator-deluxe">(x<%= x.quantity %>)</p>
        <% end %>
        
      </div>
      
      <div class="line line<%=x.id%>-form" style="display:none"> <!-- form for edit is displayed here -->
      </div>
      
      </li>
    
    <% end %>

    </ul>

  </div>

</div>
  
  <div class="block-mode" style="display:none">
    
    <%= form_for [@inv], :remote => true do |f| %>
      <br>
      <%= f.label "Plain text body, leave this blank if you wish to use the lines method" %>
      <br>
      <%= f.text_area :block, class: "block-body" %>
      <br>
    <% end %>
  
  </div>
</div>

<script>
  $(document).ready(ready);
  $(document).on('page:load', ready);
  
</script>

app/views/invs/_iframe.html.erb
<div class="iframe-inner">
  <iframe src="<%= asset_path "invs/" + @inv.id.to_s %>" width="100%" height="100%"></iframe>
</div>

app/views/invs/create.js.erb
$( ".dashboard-right" ).fadeOut( "fast", function() {
  
  $('.dashboard-right').html("<%= j (render "invs/editpage.html.erb") %>"); <!-- renders the form for the invoice you jsut made -->
  $('.left-invoices-container').html("<%= j (render "layouts/inv_search.html.erb") %>"); <!-- renders the search -->
  
  hideDiv(".dashboard-left-container")
  showDiv(".iframe-container")

  $( ".dashboard-right" ).fadeIn( 100, function() {
    $('.iframe-container').html("<%= j (render "iframe.html.erb") %>");
  })
});

app/views/invs/edit.html.erb
<div class="dashboard-container">
  <%= content_tag :div, id: 'trackers', data: {trackers: @recipients} do %>
  <% end %>
   
  <div class="dashboard-left-container" style="display:none">
    <div class="dashboard-left">
      <div class="left-inner">
        <h3>Recent Invoices</h3>
        <a href="/invs/new" data-remote="true">
          <i class="fa fa-plus-circle fa-2x"></i>
        </a>
        
      </div>
    
    <!-- for some reason i need the param here and not in the routes -->
    <%= form_tag invoice_search_path, :method => 'get', remote: true do %>
        <i class="fa fa-search"></i>
        <%= text_field_tag :search, params[:search], class: "left-search", :placeholder => "Enter the recipients name"  %>
        
    <% end %>
    
    
      <div class="left-invoices-container">
        
        <%= render "layouts/inv_search.html.erb" %>
        
      </div>
        
    </div>
  </div>
  
  <div class="left-tab" style="display:none"></div>
  <div class="right-tab" style="display:none"></div>
  
  <div class="dashboard-right-container">
    <div class="dashboard-right">
      
      <%= render "invs/editpage.html.erb" %>
    </div>
  </div>
  
  
  <div class="iframe-container" style="display:inline-block" style="display:none">
      <%= render "invs/iframe.html.erb" %>
  </div>

</div>

<script>
</script>


  

app/views/invs/new.html.erb
<div class="dashboard-container-new">
  
  <%= content_tag :div, id: 'trackers', data: {trackers: @recipients} do %>
  <% end %>
  
  <div class="dashboard-right-container">
      <div class="dashboard-right">
        
       
      <div class="right-inner-container">
        <div class="right-inner">
          <h3 class="tk-refrigerator-deluxe">Creating A New Invoice</h3>
        </div>
        
        <div class="right-inner-two">
          <h3></h3>
        </div>
      </div>
      
      <div class="right-form-container">
        
        <%= form_for (Inv.new) do |f| %>
        
        
          <div class="recipient-container-new">
            <p class="recipient-form-title-new tk-refrigerator-deluxe">Recipient</p>
            <%= f.text_field :recipient, autofocus: true, class: "recipient-form-dashboard-new tk-proxima-nova", :autocomplete => :off %>
          </div>
          
          <p class="recipient-info tk-proxima-nova"> 
            Enter the name of the person or company you're sending the invoice to,
            this should be whatever name would appear along with address on the envelope if you were to post it. 
            Additional recipients can be added later
          </p>
          
      
          <div class="divider"></div>
          
          
          <div class="date-form-container-new">
            <p class="date-form-title-new tk-refrigerator-deluxe">Sent Date</p>
            <% time = Time.new %>
            <%= f.text_field :date, class: "date-form-dashboard-new tk-proxima-nova", :autocomplete => :off, value: time.day.to_s + "-" + time.month.to_s + "-" + time.year.to_s %>
          </div>
          
          <div class="group-container-new">
            <p class="group-form-title-new tk-refrigerator-deluxe">Group </p>
            <%= f.collection_select :group_id, @group,:id,:name, :prompt => "None", class: "group-form-dashboard-new tk-proxima-nova" %>
          </div>
          
          <p class="date-info tk-proxima-nova"> 
            This field automatically dates the invoice to today, but you can change it if you'd wish. 
            You can create and add invoices to groups to make sorting them easier, or to download many invoices as a single file to aid with printing.
          </p>
          
        
          <div class="divider"></div>
          
          
          <p class="address-info tk-proxima-nova"> 
            The address of the recipient of the invoice, you should include the postcode in this field. 
            Pressing the return or enter key will take a new line.
          </p>
            
          <div class="address-container-new">
            <p class="address-form-title-new tk-refrigerator-deluxe">Address</p>
            <%= f.text_area :address_1, class: "address-form-dashboard-new tk-proxima-nova"%>
          </div>
      
      
          <%= f.submit "Create", class: "new-button-dashboard tk-refrigerator-deluxe" %>
          
        <% end %>
        
        
        
      </div>
      
  
    </div>
  </div>
</div>
      
<script>

  
  $(".date-form-dashboard").datepicker({ dateFormat: 'dd-mm-yy' }).val()
</script>

app/views/invs/search.js.erb
$('.left-invoices-container').html("<%= j (render "layouts/inv_search.html.erb") %>");
$('.dropdown-invoices-inner').html("<%= j (render "layouts/inv_search.html.erb") %>");

app/views/invs/update.js.erb
$('.dashboard-right').html("<%= j (render "invs/editpage.html.erb") %>"); <!-- renders the form for the invoice you jsut made -->
$('.left-invoices-container').html("<%= j (render "layouts/inv_search.html.erb") %>"); <!-- renders the renders the search -->

$('.alert-container').html("<%= j (render "layouts/alerts.html.erb") %>");

$('.iframe-container').html("<%= j (render "invs/iframe.html.erb") %>");<!-- renders the search -->