config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#tutorial'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get "/download/:id", to: "invs#download", as: "inv_download"
  get "/download_group/:id", to: "groups#download", as: "group_download"
  
  get "/search_invoices/", to: "invs#search", as: "invoice_search"
  
  post "/tutorial_1/", to: "users#tutorial_1", as: "tutorial_1"
  post "/tutorial_3/", to: "users#tutorial_3", as: "tutorial_3"
  get "/tutorial_complete/", to: "users#tutorial_complete", as: "tutorial_complete"
  
  
  
  
  resources :invs do
    resources :lines
  end
  
  resources :lines do
    put :order, on: :collection
  end
  
  resources :toplines do
    put :order, on: :collection
  end
  
  
  resources :users 
  resources :groups
  resources :coverimages
  
  
end

app/views/layouts/_alerts.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert tk-proxima-nova alert-<%= message_type %>"><%= message %></div>
<% end %>

<script>
  $(".alert").fadeOut(10000);
</script>

app/views/layouts/_inv_search.html.erb
<% @invs.each do |inv| %>
<a href="/invs/<%= inv.id %>/edit">
 <div class="invoice-header-container">
    <% if inv.recipient.length > 19 %>
      <p class="invoice-header-container-name tk-refrigerator-deluxe"><%= inv.recipient[0..18] + "..." %></p>
    <% else %>
      <p class="invoice-header-container-name tk-refrigerator-deluxe"><%= inv.recipient %></p>
    <% end %>
    <p class="invoice-header-container-date tk-proxima-nova"><%= inv.created_at.to_s[0..9] %></p>
  </div>
  </a>
<% end %>

<% if current_user.invs.count < 1 %>

  <div class="no-results">
    <i class="fa fa-frown-o fa-4x"></i>
    <p>You haven't made any<br>invoices yet!</p>
  </div>

<% elsif @invs.count == 0 %>
  <div class="no-results">
    <i class="fa fa-frown-o fa-4x"></i>
    <p>No items found matching <br> that search!</p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Invoice Factory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  
<script src="https://use.typekit.net/rup5qrp.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
    
</head>
<body>
  
<% if logged_in? %> <!-- header if logged in, link to sign up if not -->
 <div class="header">
   
   <i class="fa fa-file-text" id="file-icon"></i>

   
   <a href="/groups/new" style="margin: 0; padding: 0;">
    <i class="fa fa-object-group fa-3x" id="group-icon"></i>
    <div class="top-paragraph-container" id="group-paragraph-container">
      <p class="top-icon-paragraph" id="group-paragraph">Manage Groups</p>
    </div>
   </a>
    
    <a href="/invs/new" style="margin: 0; padding: 0;">
      <i class="fa fa-plus-circle fa-2x header-circle" id="invoice-icon"></i>
      <div class="top-paragraph-container" id="invoice-paragraph-container">
        <p class="top-icon-paragraph" id="invoice-paragraph">New Invoice</p>
      </div>
    </a>
    
    <a href="/users/<%=current_user.id%>/edit" style="margin: 0; padding: 0;">
      <i class="fa fa-pencil" id="edit-icon"></i>
      <div class="top-paragraph-container" id="edit-paragraph-container">
        <p class="top-icon-paragraph " id="edit-paragraph">Invoice Options</p>
      </div>
    </a>
    
    
    
    <h1 class="absolute-title tk-moby-monospaced">Invoice Factory</h1>
    <p class="user-name tk-proxima-nova"><%= current_user.name %></p>
    <i class="fa fa-user fa-3x"></i>
    
    <div class="user-dropdown">
    <%= link_to " Log Out", logout_path, method: "delete" %>
    </div>
 </div>
 
<% else %>
  <% if current_page?(controller: 'users', action: 'new') %>
    <p class="log-in-page-top-paragraph tk-proxima-nova"> Already have an account? Click <%= link_to "here", login_path %> to sign in. </p>
  <% else %>
    <p class="log-in-page-top-paragraph tk-proxima-nova"> New User? Click <%= link_to "here", new_user_path %> to create an account. </p>
  <% end %>
<% end %>


  <div class="contains-everything">
 
    <div class="alert-container">
      <%= render "layouts/alerts.html.erb" %>
    </div>
    
  <% if logged_in? %>
  
     <div class="dropdown-invoices-container" style="display:none">
      <div class="dropdown-invoices"> 
        
        <h3 class="dropdown-invoices-title tk-refrigerator-deluxe">Recent Invoices</h3>
        
        <!-- for some reason i need the param here and not in the routes -->
        <%= form_tag invoice_search_path, :method => 'get', remote: true, class: "dropdown-invoices-search" do %>
            <i class="fa fa-search"></i>
            <%= text_field_tag :search, params[:search], class: "left-search tk-proxima-nova", :placeholder => "Search by Recipient"  %>
        <% end %>
        
        <div class="dropdown-padding"></div> <!-- padding so the scroll bar looks correct -->
        
        <div class="dropdown-invoices-inner"> <!-- contains the rendered invoices -->
          <%= render "layouts/inv_search.html.erb" %>
        </div>
        
        <div class="dropdown-padding"></div> <!-- padding so the scroll bar looks correct -->
      
      </div>
     </div>
     
   <% end %>
    
    <%= yield %> <!-- the page and stuff -->
  
  </div>

</body>
</html>